include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/models/**
    - test_output/**
    - "**/*.g.dart"

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - sort_pub_dependencies

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
  rules-exclude:
    - test/**
    - test/models/**
    - test_output/**
    - "**/*.g.dart"
