builders:
  ack_generator:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackGenerator"]
    build_extensions: {".dart": [".ack.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    required_inputs: [".dart"]

# Global configuration for performance
global_options:
  ack_generator|ack_generator:
    options:
      # Enable verbose logging for debugging
      verbose: false
