builders:
  ack_schema:
    import: "package:ack_generator/builder.dart"
    builder_factories: ["ackSchemaBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source