name: ack_workspace
repository: https://github.com/btwld/ack

# sdkPath: .fvm/flutter_sdk  # Commented out for CI compatibility

packages:
  - packages/**
  - example

command:
  version:
    # Generate changelogs for the workspace
    workspaceChangelog: true
    # Link to GitHub release in changelog
    linkToCommits: true
    # Message for version commits
    message: "chore(release): publish packages\n\n{new_package_versions}"
    # Exclude example from versioning
    packageFilters:
      ignore:
        - ack_example
    # Hooks for customizing the versioning process
    hooks:
      preCommit: |
        echo "Running pre-commit hook for versioning"
        dart scripts/update_release_changelog.dart

scripts:
  analyze:
    run: melos exec -- "dart analyze . --fatal-infos"
    description: Run analyzer on all packages
    packageFilters:
      scope:
        - ack
        - ack_generator
        - ack_firebase_ai
        - ack_json_schema_builder
        - ack_example

  fix:
    run: melos exec -- "dart fix --apply"
    description: Apply fixes to all packages
    packageFilters:
      scope:
        - ack
        - ack_generator
        - ack_json_schema_builder
        - ack_example
      dependsOn:
        - "ack"  # This will ensure 'ack' is prioritized

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test"
    description: Run Dart tests for pure Dart packages
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test"
    description: Run Flutter tests for Flutter packages
    packageFilters:
      flutter: true
      dirExists: test

  format:
    run: melos exec -- "dart format . --fix"
    description: Format code for all packages

  deps-outdated:
    run: melos exec -- "dart pub outdated"
    description: Check for outdated dependencies in all packages

  # Create proper analysis_options.yaml files
  ensure_analysis_options:
    run: .scripts/ensure_analysis_options.sh
    description: Ensures each package has DCM configuration in analysis_options.yaml

  # Additional standard Melos commands
  bs:
    run: melos bootstrap
    description: Initialize the workspace with dependencies.

  clean:
    run: melos clean
    description: Clean all build outputs.

  # Build scripts for code generation
  build:
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner for all packages
    packageFilters:
      dependsOn: build_runner

  # Version and publish scripts
  # Publishing helpers
  publish:
    run: melos publish --no-dry-run --yes
    description: Publish packages to pub.dev
    
  release:
    run: |
      melos version --yes
      melos publish --no-dry-run --yes
    description: One-step version and publish

  # ACK Generator specific test commands
  test:gen:
    run: melos exec -c 1 -- dart test
    description: Run generator tests
    packageFilters:
      scope: ack_generator

  test:gen:watch:
    run: melos exec -c 1 -- dart test --watch
    description: Run generator tests in watch mode
    packageFilters:
      scope: ack_generator

  update-golden:
    run: cd packages/ack_generator && dart tool/update_goldens.dart
    description: Update golden test files (interactive - specify test names)

  update-golden:all:
    run: cd packages/ack_generator && dart tool/update_goldens.dart --all
    description: Update all golden test files

  test:golden:
    run: melos exec -c 1 -- dart test test/golden_test.dart
    description: Run only golden tests
    packageFilters:
      dirExists: test/golden

  # JSON Schema Draft-7 validation
  validate-jsonschema:
    run: |
      echo "🔧 Installing Node.js dependencies..."
      (cd tools && npm install)
      echo "🧪 Running JSON Schema Draft-7 validation tests..."
      (cd packages/ack && dart test test/json_schema_conformance_test.dart)
    description: Validate JSON Schema Draft-7 specifications

  validate-jsonschema:batch:
    run: |
      cd tools && npm install
      node jsonschema-validator.js validate-batch --input test-fixtures/schema-validation-config.json
    description: Run batch JSON Schema Draft-7 validation

  validate-jsonschema:setup:
    run: cd tools && npm install
    description: Install Node.js dependencies for JSON Schema validation

  # API compatibility checking with dart_apitool
  api-check:
    run: dart scripts/api_check.dart
    description: "Check API compatibility for packages against specified version (usage: melos api-check v0.2.0)"

  ci:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project

sdkPath: .fvm/flutter_sdk
