name: ack_workspace
repository: https://github.com/btwld/ack

packages:
  - packages/**
  - example/*

command:
  version:
    # Generate changelogs for the workspace
    workspaceChangelog: true
    # Link to GitHub release in changelog
    linkToCommits: true  
    # Message for version commits
    message: "chore(release): publish packages\n\n{new_package_versions}"
    # Hooks for customizing the versioning process
    hooks:
      preCommit: |
        # Update dependent package constraints here if needed
        echo "Running pre-commit hook for versioning"

scripts:
  analyze:
    run: melos exec -- "dart analyze . --fatal-infos"
    description: Run analyzer on all packages
    packageFilters:
      scope:
        - ack
        - ack_generator

  fix:
    run: melos exec -- "dart fix --apply"
    description: Apply fixes to all packages
    packageFilters:
      scope:
        - ack
        - ack_generator
      dependsOn:
        - "ack"  # This will ensure 'ack' is prioritized

  test:
    run: melos exec -- "dart test"
    description: Run tests for all packages
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- "dart format . --fix"
    description: Format code for all packages

  deps-outdated:
    run: melos exec -- "dart pub outdated"
    description: Check for outdated dependencies in all packages

  # Create proper analysis_options.yaml files
  ensure_analysis_options:
    run: .scripts/ensure_analysis_options.sh
    description: Ensures each package has DCM configuration in analysis_options.yaml

  # Additional standard Melos commands
  bs:
    run: melos bootstrap
    description: Initialize the workspace with dependencies.

  clean:
    run: melos clean
    description: Clean all build outputs.

  # Build scripts for code generation
  build:
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner for all packages
    packageFilters:
      dependsOn: build_runner

  # Version and publish scripts
  # Publishing helpers
  publish:
    run: melos publish --no-dry-run --yes
    description: Publish packages to pub.dev
    
  release:
    run: |
      melos version --yes
      melos publish --no-dry-run --yes
    description: One-step version and publish
