name: ack
description: A simple validation library for Dart
version: 0.0.1
repository: https://github.com/leoafarias/ack

environment:
  sdk: ^3.6.1

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  meta: ^1.15.0
