name: ack
description: A simple validation library for Dart
version: 0.0.1-dev.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  meta: ^1.15.0
