name: ack_example_test
description: Test project for ACK schema generation.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

# Using path dependencies for local development
dependencies:
  ack:
    path: ./packages/ack

dev_dependencies:
  ack_generator:
    path: ./packages/ack_generator
  build_runner: ^2.4.0
  lints: ^2.1.0
  melos: ^3.1.1
